### ISSUE TITLE
New Palette Package?

### ISSUE THREAD

**Issue by abfleishman** [EmilHvitfeldt/r-color-palettes#10]
Seems like it would be super helpful so consolidate these into a single package. Any plans to do so?

**Comment by EmilHvitfeldt** [comment]
While I have thinking about it myself I wonder how I would go about it from a practical standpoint. And I don't know the opinion towards packages which acts as collections of bits of other packages.

**Comment by abfleishman** [comment]
I have not made packages myself so I am not sure how you would go about it.  There are lots of packages out there that load functions from other packages or load many packages (e.g. tidyverse) that are meant to be used together.  As long as the packages that you would be borrowing from are credited and the packages have a license that allows for reuse etc, it seems like it would be a worthwhile contribution.

**Comment by abfleishman** [comment]
closed by the `paletteer` package https://github.com/EmilHvitfeldt/paletteer 
Good work @EmilHvitfeldt !
