### ISSUE TITLE
cartography palettes

### ISSUE THREAD

**Issue by rCarto** [EmilHvitfeldt/r-color-palettes#12]
The [cartography](https://github.com/riatelab/cartography) package provides a set of palettes for thematic cartography purposes:
```r
# Developmental version
devtools::install_github("riatelab/cartography")
# CRAN version
install.packages("cartography")

library(cartography)
display.carto.all()
```
![pal](https://user-images.githubusercontent.com/3041254/40415295-d5a48754-5e7a-11e8-9d92-f715c8893001.png)

`carto.pal()` builds sequential, diverging or qualitative color palettes. Diverging color palettes can be dissymmetric (different number of colors in each of the two gradients).

**Comment by EmilHvitfeldt** [comment]
Thank you very much for bringing this package to my attention!
