### ISSUE TITLE
shades package

### ISSUE THREAD

**Issue by rCarto** [EmilHvitfeldt/r-color-palettes#13]
The [shades](https://github.com/jonclayden/shades) package may be of interest.

> The shades package allows colours to be manipulated easily in R. Properties such as brightness and saturation can be quickly queried, changed or varied, and perceptually uniform colour gradients can be constructed. It plays nicely with the pipe operator from the popular magrittr package, and fits naturally into that paradigm.

**Comment by EmilHvitfeldt** [comment]
Thanks!
