### ISSUE TITLE
cividis palette

### ISSUE THREAD

**Issue by eliocamp** [EmilHvitfeldt/r-color-palettes#33]
I've recently came across the `cividis` palette, which is a version of viridis optimised for colour vision deficiency. 

https://github.com/marcosci/cividis

**Comment by EmilHvitfeldt** [comment]
Hello eliocamp! Thanks for your interest in this project, the cividis palette is actually included since it is part on the viridis package now.

**Comment by eliocamp** [comment]
I didn't know!: Thanks and sorry for the issue, then. :)
